### ISSUE TITLE
unable to install

### ISSUE THREAD

**Issue by md94120** [Rinoahu/SwiftOrtho#11]
The URL in install.sh file doesn't work
https://bitbucket.org/squeaky/portable-pypy/downloads/pypy-7.1.0-linux_x86_64-portable.tar.bz2

**Comment by Rinoahu** [comment]
Thanks for reporting this issue.  The URL has been fixed. Please let me know if you have any installation problems.

**Comment by md94120** [comment]
Thanks for your consideration

**Comment by md94120** [comment]
thanks a lot for your consideration
