### ISSUE TITLE
Incorporation of SwiftOrtho as Dependency

### ISSUE THREAD

**Issue by raufs** [Rinoahu/SwiftOrtho#12]
Hi Xiao, 

I am a big fan of all the technical advances you introduced for de novo ortholog finding in SwiftOrtho. 

I was wondering if it would be ok for me to include `find_orths.py` with slight modifications as part of a program I am developing. I have made sure to separate it out in the GitRepo of my program as an external tool, include your original license, and have a couple notes throughout for users to cite the SwiftOrtho paper. 

Please just let me know if you have any issues with this. 
Rauf

**Comment by Rinoahu** [comment]
sure you can if the fork is under GPLv3

**Comment by raufs** [comment]
Thank you
