### ISSUE TITLE
find_ortho.py no output

### ISSUE THREAD

**Issue by owensgl** [Rinoahu/SwiftOrtho#2]
I'm having an issue getting find_ortho.py to output anything. I ran find_hits.py fine, and got a large output file. When I try the next step, it runs for 5-10 seconds and the outputs nothing. All the temporary files are also empty. 
My command is:
`/home/owens/bin/pypy2.7-v7.0.0-linux64/bin/pypy /home/owens/bin/SwiftOrtho/bin/find_orth.py -i HanXRQv1_Ha412HO.fsa.sc -c 0.1 -y 10 > HanXRQv1_Ha412HO.fsa.sc.orth`

**Comment by Rinoahu** [comment]
Hi, owensgl.  Is there any error message shown there? If it only ran for a few seconds,  it's usually possible that some packages are missing. Do you mind to show me several lines of the HanXRQv1_Ha412HO.fsa.sc file ?

**Comment by owensgl** [comment]
I installed the prerequisites using Pypy and ` pip install -U rpython networkx scipy numpy biopython sklearn`. They seemed to work fine. 

There was no error message when running. 

My fsa.sc file looks like this:

> HanXRQCPg0579731|HAXRQ  Ha412HOChr06g0274981|HA412HO    99.11   339     3       0       15      353     2       340     1.36e-197       687     353340      0       Ha412HOChr06g0274981|HA412HO
> HanXRQCPg0579731|HAXRQ  Ha412HOChr09g0400261|HA412HO    99.11   227     2       0       127     353     1       227     1.57e-128       457     353227      0       Ha412HOChr09g0400261|HA412HO
> HanXRQCPg0579731|HAXRQ  Ha412HOChr05g0241641|HA412HO    96.47   227     8       0       127     353     1       227     1.60e-125       447     353227      0       Ha412HOChr05g0241641|HA412HO


There are a lot of really good hits, so that doesn't seem to be the issue.

**Comment by Rinoahu** [comment]
Hi, owensgl. I noticed that the length of reference protein is very long. For example, in the sample, the length of reference"Ha412HOChr06g0274981|HA412HO" is 353,340 while that of query "
HanXRQCPg0579731|HAXRQ" is 687. So, the coverage for "Ha412HOChr06g0274981|HA412HO" is below the threshold 0.1 and SwiftOrtho will ignore it. Did you apply swiftortho to protein sequences or dna sequences?

**Comment by owensgl** [comment]
If I lower the threshold to 0, it still prints nothing. Also, its not actually 353340 long. That is two columns (353 340) that were smushed together during the copy-paste. It is protein sequence for both.

**Comment by Rinoahu** [comment]
Is "HAXRQ" the species name in "HanXRQCPg0579731|HAXRQ" ? 
I fixed a bug and tested a file generated from your sample. It works on my desktop. 
Would you mind to send me a small portion of the protein sequences, so, I can test it on my own desktop.

**Comment by Rinoahu** [comment]
Hi, owensgl, have you solved the problem?

**Comment by owensgl** [comment]
I emailed back and forth with rinoahu and figured out my issue. There were two problems:
1) My protein sequence file had incorrect headers. My headers were >gene1|species1 instead of >species1|gene1.
2) I wanted to get all orthologs between two species protein sequences so I was using one set as a query and the other as the database. This didn't work. The better way to do it was to concatenate both sets (which retain species info in the header) and then use that file as both query and database, so its an all vs all comparison. Find_ortho.py takes the species into account and find orthologs correctly.
Thanks Rinoahu!
